@port=8080
@hostname=localhost
@host = {{hostname}}:{{port}}

###
POST  http://localhost:8080/site-products
Content-Type: application/json

{
    "salePrice": 2000,
    "consumerPrice": 1000
}

###
POST http://{{host}}/accounts
Content-Type: application/json

{
  "initialBalance": 0,
  "owner": "test"
}
